export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const PRINTER_GET_SUCCESS = 'PRINTER_GET_SUCCESS';
export const PRINTER_SAVE_SUCCESS = 'PRINTER_SAVE_SUCCESS';
export const PRINTER_DELETE_SUCCESS = 'PRINTER_DELETE_SUCCESS';

export const REQUEST_GET_SUCCESS = 'REQUEST_GET_SUCCESS';
export const REQUEST_SAVE_SUCCESS = 'REQUEST_SAVE_SUCCESS';
export const REQUEST_DELETE_SUCCESS = 'REQUEST_DELETE_SUCCESS';